### ISSUE TITLE
MAPA MENTAL

### ISSUE THREAD

**Issue by ANGELGARCIASANTIAGO** [SistemasTecTlaxiaco/actividad-4-mapa-mental-ANGELGARCIASANTIAGO#2]
[MAPA MENTAL ;) (1).pdf](https://github.com/user-attachments/files/17281825/MAPA.MENTAL.1.pdf)

**Comment by Ivan-PerezZ** [comment]
Exposición de Ideas Centrales:5/5
Redacción y Ortografía:5/5
Presentación visual:5/5
Referencias:5/5
Calificación Final:20/20

**Comment by josealfredo79** [comment]
Revisado..
